services:
    phpcent\Client:
        arguments:
            - http://centrifugo/api
            - '%env(CENTRIFUGO_API_KEY)%'
            - '%env(CENTRIFUGO_SECRET)%'

parameters:
    env(CENTRIFUGO_SECRET): admin
    env(CENTRIFUGO_API_KEY): admin
