services:
    phpcent\Client:
        arguments:
            - '%env(CENTRIFUGO_API_URL)%'
            - '%env(CENTRIFUGO_API_KEY)%'
            - '%env(CENTRIFUGO_SECRET)%'

parameters:
    env(CENTRIFUGO_API_URL): http://centrifugo/api
    env(CENTRIFUGO_SECRET): admin
    env(CENTRIFUGO_API_KEY): admin
