doctrine:
    dbal:
        driver:   pdo_pgsql
        charset:  UTF8
        server_version: 12.2
        host:     '%env(POSTGRES_HOST)%'
        port:     '%env(int:POSTGRES_PORT)%'
        dbname:   '%env(POSTGRES_DATABASE)%'
        user:     '%env(POSTGRES_USER)%'
        password: "%env(DATABASE_PASSWORD)%"
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Domain'
                prefix: 'App\Domain'
                alias: App

parameters:
    env(POSTGRES_HOST): postgres
    env(POSTGRES_PORT): '5432'
    env(POSTGRES_USER): gate
    env(POSTGRES_DATABASE): gate
    env(DATABASE_PASSWORD): '%env(default:default_db_password:trim:file:DATABASE_PASSWORD_FILE)%'
    env(DATABASE_PASSWORD_FILE): /run/secrets/database_password
    default_db_password: db
