framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    #http_method_override: true

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: session.handler.memcached
        cookie_secure: auto
        cookie_samesite: lax
        cookie_lifetime: 2678400 # month

    #esi: true
    #fragments: true
    php_errors:
        log: true

    lock: 'memcached://%env(SESSION_MEMCACHED_HOST)%:%env(SESSION_MEMCACHED_PORT)%'

services:
    session.memcached:
        class: Memcached
        public: true
        calls:
            - [ addServer, [ '%env(SESSION_MEMCACHED_HOST)%', '%env(SESSION_MEMCACHED_PORT)%' ]]
    session.handler.memcached:
        class:     Symfony\Component\HttpFoundation\Session\Storage\Handler\MemcachedSessionHandler
        arguments:
            - '@session.memcached'
            -
                expiretime: 2678400 # month

parameters:
    env(SESSION_MEMCACHED_HOST): 'memcached'
    env(SESSION_MEMCACHED_PORT): '11211'
