framework:
    http_client:
        scoped_clients:
            astra50httpclient:
                base_uri: https://api.astra50.ru/v1/graphql
                headers:
                    'x-hasura-admin-secret': '%env(CRM_HASURA_ADMIN_SECRET)%'
