framework:
    http_client:
        scoped_clients:
            astra50httpclient:
                base_uri: https://workflow.astra50.ru/webhook/site-gate-open
                headers:
                    'x-astra-site-secret': '%env(SITE_SECRET)%'
