hwi_oauth:
    # list of names of the firewalls in which this bundle is active, this setting MUST be set
    firewall_names: [main]

    # https://github.com/hwi/HWIOAuthBundle/blob/master/Resources/doc/2-configuring_resource_owners.md
    resource_owners:
        yandex:
            type:                yandex
            client_id:           '%env(YANDEX_ID)%'
            client_secret:       '%env(YANDEX_SECRET)%'
            options:
                csrf: true
        vkontakte:
            type:                vkontakte
            client_id:           '%env(VKONTAKTE_ID)%'
            client_secret:       '%env(VKONTAKTE_SECRET)%'
            options:
                csrf: true
        google:
            type:                google
            client_id:           '%env(GOOGLE_ID)%'
            client_secret:       '%env(GOOGLE_SECRET)%'
            scope:               "email"
        mailru:
            type:                mailru
            client_id:           '%env(MAILRU_ID)%'
            client_secret:       '%env(MAILRU_SECRET)%'
    http:
        client: httplug.oauth.client
        message_factory: httplug.oauth.client

framework:
    http_client:
        scoped_clients:
            http_oauth_client:
                scope: oauth
                max_redirects: 5

services:
    _defaults:
        public: false
        autowire: true
        autoconfigure: true

    httplug.oauth.client:
        class: Symfony\Component\HttpClient\HttplugClient
        arguments:
            - '@http_oauth_client'
