security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        entity:
            id: App\Infrastructure\DoctrineUserProvider
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            oauth:
                resource_owners:
                    vkontakte: /connect/service/vkontakte
                    yandex: /connect/service/yandex
                    google: /connect/service/google
                    mailru: /connect/service/mailru
                login_path: /login
                use_forward: false
                failure_path: /login
                oauth_user_provider:
                    service: App\Infrastructure\DoctrineUserProvider

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/connect/*, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: IS_AUTHENTICATED_REMEMBERED }
