---
kind: pipeline
type: docker
name: default

clone:
    depth: 1

steps:
    -   name: blank end line
        image: alpine:3.11.6
        commands:
            - >-
                find .
                -not -path "./.git/*"
                -not -path "./public/*"
                -not -path "./.idea/*"
                -not -path "./var/*"
                -not -path "./vendor/*"
                -type f -exec grep -Iq . {} \; -and -print0
                | xargs -0 sh -c 'test -z "$(tail -c 1 "$0")"
                || (echo "No new line at end of $0" && exit 1)'
                || exit 1
        when:
            branch:
                exclude: [ master ]

    -   name: build base node
        image: docker:20.10.1
        volumes:
            -   name: docker.sock
                path: /var/run/docker.sock
        commands:
            - docker build -t "astra50/gate-node:base" --progress=plain --target node-base .
        environment:
            DOCKER_BUILDKIT: '1'

    -   name: build base php
        image: docker:20.10.1
        volumes:
            -   name: docker.sock
                path: /var/run/docker.sock
        commands:
            - docker build -t "astra50/gate-fpm:base" --progress=plain --target php-base .
        environment:
            DOCKER_BUILDKIT: '1'

    -   name: build base nginx
        image: docker:20.10.1
        volumes:
            -   name: docker.sock
                path: /var/run/docker.sock
        commands:
            - docker build -t "astra50/gate-nginx:base" --progress=plain --target nginx-base .
        environment:
            DOCKER_BUILDKIT: '1'

    -   name: build prod
        image: docker:20.10.1
        volumes:
            -   name: docker.sock
                path: /var/run/docker.sock
        commands:
            - >-
                docker build -t "astra50/gate-fpm:${DRONE_BUILD_NUMBER}"
                --progress=plain
                --target php
                .
            - >-
                docker build -t "astra50/gate-nginx:${DRONE_BUILD_NUMBER}"
                --progress=plain
                --target nginx
                .
        environment:
            DOCKER_BUILDKIT: '1'
        depends_on:
            - build base node
            - build base php
            - build base nginx

    -   name: npm install
        image: astra50/gate-node:base
        commands:
            - npm install --no-audit
            - NODE_ENV=production node_modules/.bin/webpack
        depends_on:
            - build base node

    -   name: composer install
        image: astra50/gate-fpm:base
        commands:
            - composer install --no-interaction --no-progress --classmap-authoritative
            - bin/console cache:warmup
        environment: &test-env
            APP_ENV: test
            APP_DEBUG: 1
        depends_on:
            - build base php

    -   name: php-cs-fixer
        image: astra50/gate-fpm:base
        commands:
            - vendor/bin/php-cs-fixer fix --dry-run --diff-format udiff --using-cache=no
        when:
            branch:
                exclude: [ master ]
        depends_on:
            - composer install

    -   name: symfony requirements
        image: astra50/gate-fpm:base
        commands:
            - vendor/bin/requirements-checker
        when:
            branch:
                exclude: [ master ]
        depends_on:
            - composer install

    -   name: symfony linters
        image: astra50/gate-fpm:base
        commands:
            - bin/console lint:yaml config
            - bin/console lint:twig templates
        environment: *test-env
        depends_on:
            - composer install

    -   name: phpstan
        image: astra50/gate-fpm:base
        commands:
            - vendor/bin/phpstan analyse --configuration phpstan.neon --no-progress --memory-limit=-1
        depends_on:
            - composer install

    -   name: psalm
        image: astra50/gate-fpm:base
        commands:
            - vendor/bin/psalm --show-info=false --no-progress
        when:
            event: [ push ]
        depends_on:
            - composer install

    -   name: migration
        image: astra50/gate-fpm:base
        commands:
            - $$WAIT_FOR_IT postgres:5432
            - bin/console doctrine:migrations:migrate --no-interaction --allow-no-migration
        environment: *test-env
        depends_on:
            - composer install

    -   name: fixtures
        image: astra50/gate-fpm:base
        commands:
            - bin/console doctrine:fixtures:load --no-interaction
        environment: *test-env
        depends_on:
            - migration

    -   name: doctrine validate
        image: astra50/gate-fpm:base
        commands:
            - bin/console doctrine:schema:validate
        environment: *test-env
        depends_on:
            - migration

    -   name: phpunit
        image: astra50/gate-fpm:base
        commands:
            - vendor/bin/paratest --processes=$(nproc)
        environment: *test-env
        depends_on:
            - npm install
            - fixtures

    -   name: check deploy
        image: alpine/git:1.0.7
        commands:
            - \[ "${DRONE_COMMIT_SHA}" == "$$(git ls-remote origin ${DRONE_COMMIT_BRANCH} | awk '{ print $1}')" ] || exit 78
        when:
            branch: [ master, rc ]
        depends_on:
            - build prod
            - phpunit
            - phpstan
            - psalm
            - symfony requirements
            - doctrine validate

    -   name: deploy
        image: docker/compose:1.25.0-alpine
        volumes:
            -   name: env
                path: /drone/src/.env
            -   name: docker.sock
                path: /var/run/docker.sock
        commands:
            - docker-compose --file .swarm.yml config | docker stack deploy --prune --with-registry-auth --compose-file - gate
        environment:
            VERSION: ${DRONE_BUILD_NUMBER}
        when:
            branch: [ master, rc ]
        depends_on:
            - check deploy

    -   name: remove rc branch
        image: alpine/git:1.0.7
        commands:
            - git remote set-url origin ${DRONE_GIT_SSH_URL}
            - mkdir -p ~/.ssh -m 700
            - ssh-keyscan github.com >> ~/.ssh/known_hosts
            - echo "$GIT_SSH_KEY" > ~/.ssh/id_rsa
            - chmod 600 ~/.ssh/id_rsa
            - git push origin --delete rc
        environment:
            GIT_SSH_KEY:
                from_secret: GIT_SSH_KEY
        when:
            branch: [ rc ]
        depends_on:
            - deploy

services:
    -   name: postgres
        image: postgres:12.2
        environment:
            POSTGRES_DB: gate_test
            POSTGRES_USER: gate
            POSTGRES_PASSWORD: db
        tmpfs:
            - /var/lib/postgresql/data

volumes:
    -   name: docker.sock
        host:
            path: /var/run/docker.sock
    -   name: env
        host:
            path: /opt/secrets/astra50_gate
