version: '3.7'

services:
    nginx:
        image: astra50/gate-nginx:${VERSION}
        networks:
            - default
            - traefik
        deploy:
            mode: replicated
            replicas: 1
            endpoint_mode: dnsrr
            restart_policy:
                condition: on-failure
            update_config:
                parallelism: 1
                delay: 10s
                order: start-first
            labels:
                - "traefik.enable=true"
                - "traefik.http.routers.astra50-gate.rule=Host(`gate.astra50.ru`)"
                - "traefik.http.routers.astra50-gate.entrypoints=websecure"
                - "traefik.http.routers.astra50-gate.tls=true"
                - "traefik.http.routers.astra50-gate.tls.certresolver=leresolver"
                - "traefik.http.services.astra50-gate-service.loadbalancer.server.port=80"
                - "traefik.http.services.astra50-gate-service.loadbalancer.server.scheme=http"

    php-fpm: &app
        image: astra50/gate-fpm:${VERSION}
        environment:
            APP_SECRET: ${APP_SECRET}
            DATABASE_PASSWORD: ${DATABASE_PASSWORD}
            VKONTAKTE_ID: ${VKONTAKTE_ID}
            VKONTAKTE_SECRET: ${VKONTAKTE_SECRET}
            YANDEX_ID: ${YANDEX_ID}
            YANDEX_SECRET: ${YANDEX_SECRET}
            GOOGLE_ID: ${GOOGLE_ID}
            GOOGLE_SECRET: ${GOOGLE_SECRET}
            INSTAGRAM_ID: ${INSTAGRAM_ID}
            INSTAGRAM_SECRET: ${INSTAGRAM_SECRET}
            MAILRU_ID: ${MAILRU_ID}
            MAILRU_PRIVATE: ${MAILRU_PRIVATE}
            MAILRU_SECRET: ${MAILRU_SECRET}
            CENTRIFUGO_SECRET: ${CENTRIFUGO_SECRET}
            CENTRIFUGO_API_KEY: ${CENTRIFUGO_API_KEY}
            CENTRIFUGO_ADMIN_PASSWORD: ${CENTRIFUGO_ADMIN_PASSWORD}
            CENTRIFUGO_ADMIN_SECRET: ${CENTRIFUGO_ADMIN_SECRET}
            UISCOM_TOKEN: ${UISCOM_TOKEN}
            SENTRY_DSN: ${SENTRY_DSN}
        stop_grace_period: 120s
        deploy:
            mode: replicated
            replicas: 1
            endpoint_mode: dnsrr
            restart_policy:
                condition: on-failure
            update_config:
                parallelism: 1
                delay: 10s
                order: start-first

    migration:
        <<: *app
        command: wait-for-it.sh postgres:5432 -- console doctrine:migrations:migrate --no-interaction --allow-no-migration
        deploy:
            mode: replicated
            replicas: 1
            restart_policy:
                condition: none
            labels:
                - "traefik.enable=false"

    postgres:
        image: postgres:12.2
        volumes:
            -   type: bind
                source: /opt/astra50/db/gate
                target: /var/lib/postgresql/data
            -   type: bind
                source: /opt/am/db/backups
                target: /backups
        environment:
            POSTGRES_DB: db
            POSTGRES_USER: db
            POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
        deploy:
            mode: global
            update_config:
                failure_action: rollback
                parallelism: 1
                delay: 5s
        healthcheck:
            test: pg_isready
            interval: 5s
            timeout: 5s
            retries: 3
            start_period: 10s

    memcached:
        image: memcached:1.6.9-alpine
        healthcheck:
            test: nc -z 127.0.0.1 11211
            interval: 5s
            timeout: 5s
            retries: 3
            start_period: 5s

    centrifugo:
        image: centrifugo/centrifugo:v2.7.0
        environment:
            CENTRIFUGO_PORT: 80
            CENTRIFUGO_ADMIN: 'true'
            CENTRIFUGO_TOKEN_HMAC_SECRET_KEY: ${CENTRIFUGO_SECRET}
            CENTRIFUGO_API_KEY: ${CENTRIFUGO_API_KEY}
            CENTRIFUGO_ADMIN_PASSWORD: ${CENTRIFUGO_ADMIN_PASSWORD}
            CENTRIFUGO_ADMIN_SECRET: ${CENTRIFUGO_ADMIN_SECRET}
        networks:
            - traefik
            - default
        deploy:
            mode: replicated
            replicas: 1
            endpoint_mode: dnsrr
            update_config:
                order: start-first
                failure_action: rollback
                parallelism: 1
                delay: 5s
            labels:
                - "traefik.enable=true"
                - "traefik.http.routers.astra50-centrifugo.rule=Host(`centrifugo.astra50.ru`)"
                - "traefik.http.routers.astra50-centrifugo.entrypoints=websecure"
                - "traefik.http.routers.astra50-centrifugo.tls=true"
                - "traefik.http.routers.astra50-centrifugo.tls.certresolver=leresolver"
                - "traefik.http.services.astra50-centrifugo-service.loadbalancer.server.port=80"
                - "traefik.http.services.astra50-centrifugo-service.loadbalancer.server.scheme=http"

networks:
    traefik:
        external: true
        name: traefik
    default:
        driver: overlay
        name: astra50gate
