version: '3.7'

services:
    nginx:
        image: astra50/gate-nginx:base
        build:
            context: .
            target: nginx-base
        labels:
            ru.grachevko.dhu: 'gate.astra50.local:2'
        volumes:
            - ./public:/usr/local/app/public
            - ./etc/nginx.conf:/etc/nginx/nginx.conf
            - ./etc/nginx.default.conf:/etc/nginx/templates/default.conf.template

    php-fpm:
        image: astra50/gate-fpm:base
        build:
            context: .
            target: php-fpm-base
        volumes:
            - ./:/usr/local/app
            - ./etc/php.ini:/usr/local/etc/php/php.ini
            - ./etc/php-fpm.conf:/usr/local/etc/php-fpm.d/default.conf
        environment:
            APP_ENV: dev
            APP_DEBUG: 1
            PHP_OPCACHE_ENABLE: 0

    node:
        image: astra50/gate-node:base
        command: webpack --watch
        volumes:
            - ./:/usr/local/app

    postgres:
        image: postgres:12.2
        labels:
            ru.grachevko.dhu: 'db.gate.astra50.local'
        volumes:
            -   type: tmpfs
                target: /var/lib/postgresql/data
                tmpfs:
                    size: 2G
            - ./:/usr/local/app
        environment:
            POSTGRES_DB: gate
            POSTGRES_USER: gate
            POSTGRES_PASSWORD: db
        healthcheck:
            test: pg_isready -U db
            interval: 5s
            timeout: 5s
            retries: 3
            start_period: 10s

    memcached:
        image: memcached:1.6.9-alpine

    centrifugo:
        image: centrifugo/centrifugo:v2.7.0
        labels:
            ru.grachevko.dhu: 'centrifugo.astra50.local'
        environment:
            CENTRIFUGO_PORT: 80
            CENTRIFUGO_ADMIN: 'true'
            CENTRIFUGO_TOKEN_HMAC_SECRET_KEY: admin
            CENTRIFUGO_API_KEY: admin
            CENTRIFUGO_ADMIN_PASSWORD: admin
            CENTRIFUGO_ADMIN_SECRET: admin

networks:
    default:
        name: astra50_gate
        ipam:
            config:
                -   subnet: 192.168.63.0/24
