parameters:
    env(UISCOM_TOKEN): null

services:
    _defaults:
        autowire: true 
        autoconfigure: true
    
    App\:
        resource: '../src/*'
    
    App\Ports\Controller\:
        resource: '../src/Ports/Controller'
        tags: ['controller.service_arguments']

    App\Infrastructure\Centrifugo\PhpcentCentrifugo: ~
    App\Infrastructure\Centrifugo\Centrifugo: '@App\Infrastructure\Centrifugo\PhpcentCentrifugo'

    App\Infrastructure\Gate\UiscomGate:
        arguments:
            - '@uiscom'
            - '%env(UISCOM_TOKEN)%'
