parameters:
    env(CRM_HASURA_ADMIN_SECRET): null

services:
    _defaults:
        autowire: true 
        autoconfigure: true
    
    App\:
        resource: '../src/*'
    
    App\Ports\Controller\:
        resource: '../src/Ports/Controller'
        tags: ['controller.service_arguments']

    App\Infrastructure\Centrifugo\PhpcentCentrifugo: ~
    App\Infrastructure\Centrifugo\Centrifugo: '@App\Infrastructure\Centrifugo\PhpcentCentrifugo'

    App\Infrastructure\Gate\AstraApiGate:
        arguments:
            - '@astra50httpclient'
