parameters:
    env(UISCOM_TOKEN): null

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Ports\Controller\:
        resource: '../src/Ports/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Infrastructure\Centrifugo\PhpcentCentrifugo: ~
    App\Infrastructure\Centrifugo\Centrifugo: '@App\Infrastructure\Centrifugo\PhpcentCentrifugo'

    App\Infrastructure\Gate\UiscomGate:
        arguments:
            - '@uiscom'
            - '%env(UISCOM_TOKEN)%'
